# Generated by Django 5.0.3 on 2024-03-30 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='biografia',
            field=models.TextField(blank=True),
        ),
    ]
