# Generated by Django 5.0.3 on 2024-03-30 18:37

import usuarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_usuario_nome_completo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='photo_icon',
            field=models.CharField(default='caveira.svg', max_length=255),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=usuarios.models.upload_to),
        ),
    ]
