# Generated by Django 5.0.3 on 2024-03-30 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_usuario_photo_icon_alter_usuario_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='photo_icon',
        ),
    ]
