# Generated by Django 5.0.3 on 2024-03-30 18:46

import usuarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_usuario_photo_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='photo_icon',
            field=models.ImageField(blank=True, null=True, upload_to=usuarios.models.upload_to),
        ),
    ]
