# Generated by Django 5.0.3 on 2024-03-30 18:53

import usuarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_alter_usuario_photo_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='photo_icon',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='photo',
            field=models.ImageField(blank=True, upload_to=usuarios.models.upload_to),
        ),
    ]
