# Generated by Django 5.0.3 on 2024-03-31 04:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_remove_usuario_photo_icon_alter_usuario_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='seguidores',
            field=models.ManyToManyField(related_name='seguindo', to=settings.AUTH_USER_MODEL),
        ),
    ]
