# Generated by Django 5.0.3 on 2024-03-31 04:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_usuario_seguidores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='seguidores',
        ),
        migrations.AddField(
            model_name='usuario',
            name='seguindo',
            field=models.ManyToManyField(related_name='seguidores', to=settings.AUTH_USER_MODEL),
        ),
    ]
