# Generated by Django 5.0.3 on 2024-04-28 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colecoes', '0004_colecao_likes_comentario'),
        ('usuarios', '0011_remove_usuario_seguidores_usuario_seguindo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='colecoes_salvas',
            field=models.ManyToManyField(related_name='usuarios_que_salvaram', to='colecoes.colecao'),
        ),
    ]
