# Generated by Django 5.0.3 on 2024-05-16 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colecoes', '0009_merge_20240505_2114'),
        ('usuarios', '0013_usuario_seguidores_alter_usuario_seguindo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='colecoes_salvas',
            field=models.ManyToManyField(blank=True, related_name='usuarios_que_salvaram', to='colecoes.colecao'),
        ),
    ]
