# Generated by Django 5.0.3 on 2024-03-30 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colecoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nome',
            field=models.CharField(choices=[('Livros', 'Livros'), ('Filmes', 'Filmes'), ('Músicas', 'Músicas'), ('Jogos', 'Jogos'), ('Selos', 'Selos'), ('Moedas', 'Moedas'), ('Quadrinhos', 'Quadrinhos'), ('Carros', 'Carros'), ('Vinhos', 'Vinhos'), ('Cartas', 'Cartas'), ('Miniaturas', 'Miniaturas'), ('Brinquedos', 'Brinquedos'), ('Antiguidades', 'Antiguidades'), ('Relógios', 'Relógios'), ('Jóias', 'Jóias'), ('Instrumentos Musicais', 'Instrumentos Musicais'), ('Artes', 'Artes'), ('Itens Esportivos', 'Itens Esportivos'), ('Eletrônicos', 'Eletrônicos'), ('Vestuário', 'Vestuário'), ('Acessórios', 'Acessórios'), ('Cosméticos', 'Cosméticos'), ('Utensílios Domésticos', 'Utensílios Domésticos'), ('Decoração', 'Decoração'), ('Móveis', 'Móveis'), ('Eletrodomésticos', 'Eletrodomésticos'), ('Ferramentas', 'Ferramentas'), ('Brindes', 'Brindes'), ('Peças Religiosas', 'Peças Religiosas'), ('Charutos', 'Charutos'), ('Chaveiros', 'Chaveiros'), ('Pedras Preciosas', 'Pedras Preciosas'), ('Plantas', 'Plantas'), ('Artefatos Históricos', 'Artefatos Históricos'), ('Culinária', 'Culinária'), ('Outros', 'Outros')], max_length=100),
        ),
    ]
