# Generated by Django 5.0.3 on 2024-03-15 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colecoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacao',
            name='publicada',
            field=models.BooleanField(default=False),
        ),
    ]
