# Generated by Django 5.0.3 on 2024-03-30 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colecoes', '0002_alter_categoria_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colecao',
            name='cor',
            field=models.CharField(choices=[('#FFCA2C', 'Amarelo Claro'), ('#D9C95B', 'Amarelo Escuro'), ('#D9AA5B', 'Laranja Claro'), ('#D9D2A3', 'Areia'), ('#004FFF', 'Azul Marinho'), ('#5300FF', 'Roxo'), ('#5B5BD9', 'Lilás'), ('#5BABD9', 'Azul Claro'), ('#8F00DB', 'Uva'), ('#A3A3D9', 'Lilás Claro'), ('#FF0049', 'Vermelho'), ('#FF4400', 'Laranja Neon'), ('#D9675B', 'Laranja Claro'), ('#D95BCA', 'Rosa'), ('#DB6100', 'Laranja Escuro'), ('#D9A8A3', 'Bege')], default='#FFCA2C', max_length=7),
        ),
    ]
