# Generated by Django 5.0.3 on 2024-03-28 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colecoes', '0004_alter_publicacao_autor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Publicacao',
        ),
    ]
