# Generated by Django 5.0.3 on 2024-04-28 23:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colecoes', '0004_colecao_likes_comentario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colecao',
            name='likes',
        ),
        migrations.AddField(
            model_name='colecao',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='colecoes_curtidas', to=settings.AUTH_USER_MODEL),
        ),
    ]
