# Generated by Django 5.0.3 on 2024-03-29 03:24

import colorfield.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colecoes', '0006_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Colecao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('cor', colorfield.fields.ColorField(default='#FFF1C0', image_field=None, max_length=25, samples=None)),
                ('categoria', models.CharField(choices=[('LIVROS', 'Livros'), ('FILMES', 'Filmes'), ('MÚSICAS', 'Músicas'), ('JOGOS', 'Jogos'), ('SELOS', 'Selos'), ('MOEDAS', 'Moedas'), ('QUADRINHOS', 'Quadrinhos'), ('CARROS', 'Carros'), ('VINHOS', 'Vinhos'), ('CARTAS', 'Cartas'), ('MINIATURAS', 'Miniaturas'), ('BRINQUEDOS', 'Brinquedos'), ('ANTIGUIDADES', 'Antiguidades'), ('RELÓGIOS', 'Relógios'), ('JÓIAS', 'Jóias'), ('INSTRUMENTOS_MUSICAIS', 'Instrumentos Musicais'), ('ARTES', 'Artes'), ('ITENS_ESPORTIVOS', 'Itens Esportivos'), ('ELETRÔNICOS', 'Eletrônicos'), ('VESTUÁRIO', 'Vestuário'), ('ACESSÓRIOS', 'Acessórios'), ('COSMÉTICOS', 'Cosméticos'), ('UTENSÍLIOS_DOMÉSTICOS', 'Utensílios Domésticos'), ('DECORAÇÃO', 'Decoração'), ('MÓVEIS', 'Móveis'), ('ELETRODOMÉSTICOS', 'Eletrodomésticos'), ('FERRAMENTAS', 'Ferramentas'), ('BRINDES', 'Brindes'), ('PEÇAS_RELIGIOSAS', 'Peças Religiosas'), ('CHARUTOS', 'Charutos'), ('CHAVEIROS', 'Chaveiros'), ('PEDRAS_PRECIOSAS', 'Pedras Preciosas'), ('PLANTAS', 'Plantas'), ('ARTEFATOS_HISTÓRICOS', 'Artefatos Históricos'), ('CULINÁRIA', 'Culinária'), ('OUTROS', 'Outros')], default='OUTROS', max_length=100)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('status_colecao', models.BooleanField(default=True)),
                ('privacidade_colecao', models.BooleanField(default=False)),
                ('tags', models.CharField(blank=True, max_length=100)),
                ('orcamento_colecao', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('localizacao_colecao', models.CharField(blank=True, max_length=100)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('nome', 'usuario')},
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('categoria', models.CharField(choices=[('LIVROS', 'Livros'), ('FILMES', 'Filmes'), ('MÚSICAS', 'Músicas'), ('JOGOS', 'Jogos'), ('SELOS', 'Selos'), ('MOEDAS', 'Moedas'), ('QUADRINHOS', 'Quadrinhos'), ('CARROS', 'Carros'), ('VINHOS', 'Vinhos'), ('CARTAS', 'Cartas'), ('MINIATURAS', 'Miniaturas'), ('BRINQUEDOS', 'Brinquedos'), ('ANTIGUIDADES', 'Antiguidades'), ('RELÓGIOS', 'Relógios'), ('JÓIAS', 'Jóias'), ('INSTRUMENTOS_MUSICAIS', 'Instrumentos Musicais'), ('ARTES', 'Artes'), ('ITENS_ESPORTIVOS', 'Itens Esportivos'), ('ELETRÔNICOS', 'Eletrônicos'), ('VESTUÁRIO', 'Vestuário'), ('ACESSÓRIOS', 'Acessórios'), ('COSMÉTICOS', 'Cosméticos'), ('UTENSÍLIOS_DOMÉSTICOS', 'Utensílios Domésticos'), ('DECORAÇÃO', 'Decoração'), ('MÓVEIS', 'Móveis'), ('ELETRODOMÉSTICOS', 'Eletrodomésticos'), ('FERRAMENTAS', 'Ferramentas'), ('BRINDES', 'Brindes'), ('PEÇAS_RELIGIOSAS', 'Peças Religiosas'), ('CHARUTOS', 'Charutos'), ('CHAVEIROS', 'Chaveiros'), ('PEDRAS_PRECIOSAS', 'Pedras Preciosas'), ('PLANTAS', 'Plantas'), ('ARTEFATOS_HISTÓRICOS', 'Artefatos Históricos'), ('CULINÁRIA', 'Culinária'), ('OUTROS', 'Outros')], default='OUTROS', max_length=100)),
                ('estado', models.CharField(blank=True, max_length=100)),
                ('data_aquisicao', models.DateField(blank=True, null=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tags', models.CharField(blank=True, max_length=100)),
                ('numero_serie', models.CharField(blank=True, max_length=100)),
                ('ano_fabricacao', models.CharField(blank=True, max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_itens/')),
                ('notas_adicionais', models.TextField(blank=True)),
                ('colecao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='colecoes.colecao')),
            ],
        ),
        migrations.DeleteModel(
            name='Publicacao',
        ),
    ]
