# Generated by Django 5.0.3 on 2024-05-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colecoes', '0006_busca'),
    ]

    operations = [
        migrations.AddField(
            model_name='colecao',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_colecoes/'),
        ),
    ]
