# Generated by Django 5.0.3 on 2024-05-02 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colecoes', '0007_tag_remove_colecao_tags_colecao_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colecao',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AddField(
            model_name='colecao',
            name='tags',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
