# Generated by Django 5.0.3 on 2024-05-06 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colecoes', '0007_colecao_foto'),
        ('colecoes', '0008_remove_colecao_tags_delete_tag_colecao_tags'),
    ]

    operations = [
    ]
